version: '3.8'

services:
  # Fluentd collects logs from the photoupload app
  fluentd:
    image: fluent/fluentd:v1.14-1
    ports:
      - "24224:24224"
    volumes:
      - ./fluentd:/fluentd/etc/
    networks:
      - monitoring_network

  # Prometheus collects metrics from the photoupload app
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - "9090:9090"
    networks:
      - monitoring_network

  # Grafana for visualizing metrics from Prometheus
  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: 'admin'
    ports:
      - "3000:3000"
    networks:
      - monitoring_network

  # Mailhog for capturing emails from the application
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI
    networks:
      - monitoring_network

networks:
  monitoring_network:
    driver: bridge
